name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    name: build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        run: rustup update stable && rustup default stable
      - run: sudo apt-get update && sudo apt-get install aspell aspell-en
      - name: Install mdbook
        uses: taiki-e/install-action@mdbook
      - name: Install mdbook-linkcheck
        uses: taiki-e/install-action@mdbook-linkcheck
      - run: bash ci/spellcheck.sh list
      - run: mdbook build
      - run: cargo test --all --manifest-path=./examples/Cargo.toml --target-dir ./target
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book

