name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    name: build and test
    env:
      MDBOOK_LINKCHECK_VERSION: 0.7.0
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        run: rustup update stable && rustup default stable
      - run: sudo apt-get update && sudo apt-get install aspell aspell-en
      - name: Install mdbook and mdbook-linkcheck
        run: |
          tag=$(curl -LsSf https://api.github.com/repos/rust-lang/mdBook/releases/latest | jq -r '.tag_name')
          curl -LsSf https://github.com/rust-lang/mdBook/releases/download/$tag/mdbook-$tag-x86_64-unknown-linux-gnu.tar.gz | tar xzf -
          curl -LsSf https://github.com/Michael-F-Bryan/mdbook-linkcheck/releases/download/v${MDBOOK_LINKCHECK_VERSION}/mdbook-linkcheck-v${MDBOOK_LINKCHECK_VERSION}-x86_64-unknown-linux-gnu.tar.gz | tar xzf -
          echo $(pwd) >> $GITHUB_PATH
      #- run: bash ci/spellcheck.sh list
      - run: cp src/SUMMARY_zh.md src/SUMMARY.md
      - run: mdbook build
      - run: cargo test --all --manifest-path=./examples/Cargo.toml --target-dir ./target
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book

